import { useState, useEffect } from "react";
import type { ActionFunctionArgs, LoaderFunctionArgs, HeadersFunction } from "react-router";
import { useLoaderData, useFetcher } from "react-router";
import { useAppBridge } from "@shopify/app-bridge-react";
import { authenticate } from "../shopify.server";
import { boundary } from "@shopify/shopify-app-react-router/server";
import db from "../db.server";
import { AI_PROVIDER_LABELS, OFFER_TYPE_LABELS } from "../lib/utils/constants";
import styles from "../styles/analytics.module.css";
import dashStyles from "../styles/dashboard.module.css";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { session } = await authenticate.admin(request);

  let shop = await db.shop.findUnique({
    where: { shopDomain: session.shop },
  });

  if (!shop) {
    shop = await db.shop.create({
      data: { shopDomain: session.shop },
    });
  }

  const hasApiKey = !!shop.aiApiKey;
  const recentOffers = await db.offer.findMany({
    where: { shopId: shop.id, aiGenerated: true },
    orderBy: { createdAt: "desc" },
    take: 10,
  });

  return {
    aiEnabled: shop.enableAi,
    aiProvider: shop.aiProvider,
    hasApiKey,
    recentAiOffers: recentOffers,
  };
};

export const action = async ({ request }: ActionFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const formData = await request.formData();
  const intent = formData.get("intent") as string;

  const shop = await db.shop.findUnique({
    where: { shopDomain: session.shop },
  });

  if (!shop) {
    return { error: "Shop not found" };
  }

  if (intent === "generate") {
    // In a real implementation, this would call the AI provider
    // For now, return mock suggestions
    const mockSuggestions = [
      {
        headline: "Complete Your Look",
        description:
          "Customers who bought similar items also loved these complementary products.",
        type: "bundle",
        discountType: "percentage",
        discountValue: 15,
        reasoning:
          "Based on purchase patterns, bundling complementary items with a 15% discount increases conversion by 2-3x compared to single product offers.",
      },
      {
        headline: "Exclusive Add-On Deal",
        description: "Add this popular accessory to your order at a special price.",
        type: "single",
        discountType: "fixed",
        discountValue: 5,
        reasoning:
          "Low-cost accessories with a fixed discount have the highest acceptance rate for first-time buyers.",
      },
      {
        headline: "VIP Bundle Upgrade",
        description:
          "Upgrade your order with our best-selling bundle — save more when you buy together.",
        type: "bundle",
        discountType: "percentage",
        discountValue: 20,
        reasoning:
          "Premium bundles with 20% off perform well for orders above the average order value, targeting high-intent customers.",
      },
    ];

    return { suggestions: mockSuggestions };
  }

  if (intent === "createFromSuggestion") {
    const headline = formData.get("headline") as string;
    const description = formData.get("description") as string;
    const type = formData.get("type") as string;
    const discountType = (formData.get("discountType") as string) || null;
    const discountValue = formData.get("discountValue")
      ? parseFloat(formData.get("discountValue") as string)
      : null;

    await db.offer.create({
      data: {
        shopId: shop.id,
        name: `AI: ${headline.slice(0, 50)}`,
        type,
        status: "draft",
        productIds: "[]",
        headline,
        description,
        discountType,
        discountValue,
        aiGenerated: true,
        aiPrompt: "Auto-generated by AfterPulse AI",
      },
    });

    return { success: true, created: true };
  }

  return { error: "Unknown action" };
};

export default function AiRulesPage() {
  const { aiEnabled, aiProvider, hasApiKey, recentAiOffers } =
    useLoaderData<typeof loader>();
  const shopify = useAppBridge();
  const fetcher = useFetcher<typeof action>();

  const suggestions = fetcher.data?.suggestions;
  const isGenerating =
    fetcher.state === "submitting" &&
    fetcher.formData?.get("intent") === "generate";

  useEffect(() => {
    if (fetcher.data?.created) {
      shopify.toast.show("AI offer created as draft!");
    }
  }, [fetcher.data, shopify]);

  return (
    <s-page heading="AI Smart Rules">
      <s-button
        slot="primary-action"
        href="/app/settings"
      >
        Configure AI
      </s-button>

      {/* Status */}
      <s-section>
        <div
          className={`${styles["ai-config-status"]} ${
            hasApiKey && aiEnabled
              ? styles["ai-config-status--connected"]
              : styles["ai-config-status--disconnected"]
          }`}
        >
          {hasApiKey && aiEnabled
            ? `✓ AI powered by ${AI_PROVIDER_LABELS[aiProvider] || aiProvider}`
            : !aiEnabled
              ? "✗ AI is currently disabled — enable it in Settings"
              : "✗ No API key configured — add one in Settings"}
        </div>
      </s-section>

      {/* Generate Suggestions */}
      <s-section heading="Generate Offer Suggestions">
        <s-stack direction="block" gap="base">
          <s-paragraph>
            Let AI analyze your store's products and customer patterns to suggest
            high-converting upsell offers tailored to your catalog.
          </s-paragraph>
          <fetcher.Form method="post">
            <input type="hidden" name="intent" value="generate" />
            <s-button
              type="submit"
              variant="primary"
              {...(isGenerating ? { loading: true } : {})}
              disabled={!aiEnabled || !hasApiKey || undefined}
            >
              🤖 Generate Suggestions
            </s-button>
          </fetcher.Form>
        </s-stack>
      </s-section>

      {/* AI Suggestions Results */}
      {suggestions && suggestions.length > 0 && (
        <s-section heading="AI Suggestions">
          <s-stack direction="block" gap="base">
            {suggestions.map(
              (
                suggestion: {
                  headline: string;
                  description: string;
                  type: string;
                  discountType: string | null;
                  discountValue: number | null;
                  reasoning: string;
                },
                index: number,
              ) => (
                <div key={index} className={styles["ai-suggestion-card"]}>
                  <div className={styles["ai-suggestion-card__header"]}>
                    <div>
                      <div className={styles["ai-suggestion-card__headline"]}>
                        {suggestion.headline}
                      </div>
                      <div className={styles["ai-suggestion-card__description"]}>
                        {suggestion.description}
                      </div>
                    </div>
                    <span className={styles["ai-suggestion-card__type"]}>
                      {OFFER_TYPE_LABELS[suggestion.type] || suggestion.type}
                    </span>
                  </div>
                  <div className={styles["ai-suggestion-card__reasoning"]}>
                    💡 {suggestion.reasoning}
                  </div>
                  {suggestion.discountType && suggestion.discountValue && (
                    <s-paragraph>
                      <s-text>Suggested discount: </s-text>
                      <s-text fontWeight="bold">
                        {suggestion.discountType === "percentage"
                          ? `${suggestion.discountValue}% off`
                          : `$${suggestion.discountValue} off`}
                      </s-text>
                    </s-paragraph>
                  )}
                  <fetcher.Form method="post" style={{ marginTop: "0.75rem" }}>
                    <input type="hidden" name="intent" value="createFromSuggestion" />
                    <input type="hidden" name="headline" value={suggestion.headline} />
                    <input
                      type="hidden"
                      name="description"
                      value={suggestion.description}
                    />
                    <input type="hidden" name="type" value={suggestion.type} />
                    <input
                      type="hidden"
                      name="discountType"
                      value={suggestion.discountType || ""}
                    />
                    <input
                      type="hidden"
                      name="discountValue"
                      value={suggestion.discountValue?.toString() || ""}
                    />
                    <s-button type="submit" variant="primary">
                      Create as Draft
                    </s-button>
                  </fetcher.Form>
                </div>
              ),
            )}
          </s-stack>
        </s-section>
      )}

      {/* Recent AI Offers */}
      <s-section slot="aside" heading="Recent AI Offers">
        {recentAiOffers.length > 0 ? (
          <s-stack direction="block" gap="tight">
            {recentAiOffers.map((offer) => (
              <div key={offer.id} style={{ padding: "0.5rem 0" }}>
                <s-link href={`/app/offers/${offer.id}`}>{offer.name}</s-link>
                <div style={{ fontSize: "0.75rem", color: "#64748b" }}>
                  <span
                    className={`${dashStyles["status-badge"]} ${
                      dashStyles[`status-badge--${offer.status}`]
                    }`}
                  >
                    {offer.status}
                  </span>
                </div>
              </div>
            ))}
          </s-stack>
        ) : (
          <s-paragraph>
            No AI-generated offers yet. Click "Generate Suggestions" to get started.
          </s-paragraph>
        )}
      </s-section>

      <s-section slot="aside" heading="How It Works">
        <s-unordered-list>
          <s-list-item>AI analyzes your product catalog and order history</s-list-item>
          <s-list-item>It identifies complementary products and buying patterns</s-list-item>
          <s-list-item>Suggestions include optimal discount levels and headlines</s-list-item>
          <s-list-item>Review and activate offers with one click</s-list-item>
        </s-unordered-list>
      </s-section>
    </s-page>
  );
}

export const headers: HeadersFunction = (headersArgs) => {
  return boundary.headers(headersArgs);
};
